### ISSUE TITLE
GitHub Pages Documentation

### ISSUE THREAD

**Issue by jmwright** [fragmuffin/cqparts#27] opened 2017-11-23 12:38 UTC
Shouldn't the contents of the docs directory be available here? http://fragmuffin.github.io/cqparts

Have you just not flipped that switch yet, or are the docs hosted somewhere else or under a custom domain name?

**Comment by fragmuffin** [comment] 2017-11-23 13:05
@jmwright 
I planned to do it closer to release #25.
But i can publish them now if you'd like.
They'll just be constantly changing.

**Comment by fragmuffin** [comment] 2017-11-23 13:08
Closed as duplicate of #25

**Closed by fragmuffin** 2017-11-23 13:08 UTC
Labels: duplicate
